--- # Default onebutton configuration
global:
  log:
    verbose: null # true - verbose, false - not verbose, null - middle
  dir:
    logs: ~/.local/onebutton/logs # Used to place processes err & out logs
    pids: ~/.local/onebutton/pids # Used to place processes pid files

Button:
  - name: FootSwitch
    type: gpio
#    path: /some/dir/plugin # Path to required plugin directory
    config:
      fixed: false # Button with (only push event) or without (support push and long push events) fixation
      args: # Plugin arguments list
        - 99 # connected GPIO pin (second wire connected to GND)

Display:
  - name: RGB8x8Display
    type: ttyusb
#    path: /some/dir/plugin # Path to required plugin directory
    config:
      args: # Plugin arguments list
        - /dev/ttyUSB0 # Display device

Jack:
  - name: esi-ugm96
    type: alsa # Type of jackd driver
    config:
      rtpriority: 89 # Int or False to disable realtime mode
      device: hw:1 # Alsa device to capture
      samplerate: 44100
      buffer: 128
      periods: 3

Guitarix:
  - name: guitar1
    rpc_port: 8881 # Port to handle by json-rpc
    jack: esi-ugm96 # Connect to jackd with this name
    mapping:
      inputs:
        - type: audio
          in: 1
        - type: audio
          in: 2
      outputs:
        - type: audio
          out: 1
        - type: audio
          out: 2
