--- # Default onebutton configuration
global:
  log:
    verbose: true # true - verbose, false - not verbose, null - middle
  dir:
    logs: ~/.local/share/onebutton/logs # Used to place processes err & out logs
    pids: ~/.local/share/onebutton/pids # Used to place processes pid files

Button:
  - name: FootSwitch
    type: gpio
#    path: /some/dir/plugin # Path to required plugin directory
    config:
      fixed: false # Button with (only push event) or without (support push and long push events) fixation
      args: # Plugin arguments list
        - 225 # connected GPIO pin (second wire connected to GND)

Display:
  - name: RGB8x8Display
    type: ttyusb
#    path: /some/dir/plugin # Path to required plugin directory
    config:
      args: # Plugin arguments list
        - /dev/ttyUSB0 # Display device

Jack:
  - name: esi-ugm96
    type: alsa # Type of jackd driver
    config:
      rtpriority: 89 # Int or False to disable realtime mode
      device: hw:1 # Alsa device to capture
      samplerate: 44100
      buffer: 128
      periods: 3

Guitarix:
  - name: guitar1
    rpc_port: 8881 # Port to handle by json-rpc
    web: 8000 # Web interface port or false to disable
    jack: esi-ugm96 # Connect to jackd with this name
    mapping:
      inputs: # Basically you can use "amp", or "fx" to skip amp. Be carefully - "amp" has (0) in and (0) out, fx has (0) in and (0,1) out
        - type: audio
          module: amp # amp or fx
          in: 0
          out: 1
        - type: audio
          module: amp
          in: 0
          out: 2
      outputs:
        - type: audio
          module: fx
          out: 0
          in: 1
        - type: audio
          module: fx
          out: 1
          in: 2

Bluetooth:
  - name: OneButton
    dev: hci0 # Bluetooth device name
    enabled: true # Up & running
    encrypt: true # Encrypt bluetooth link
    visible: true # Visible to device scan
